#!/bin/bash
# Generates STATUS.md showing current Claude Code configuration

set -e

OUTPUT=".claude/STATUS.md"

# Colors for terminal output (not used in STATUS.md)
GREEN='\033[0;32m'
NC='\033[0m'

# Count functions
count_core_agents() {
  find .claude/core/agents -name "*.md" -not -path "*/docs/*" 2>/dev/null | wc -l | tr -d ' '
}

count_core_commands() {
  find .claude/core/commands -name "*.md" 2>/dev/null | wc -l | tr -d ' '
}

count_enabled_skills() {
  find .claude/core/skills -name "skill.md" -o -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' '
}

count_example_skills() {
  find .claude/examples/skills -name "skill.md" -o -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' '
}

count_active_hooks() {
  if [ -f ".claude/settings.json" ]; then
    grep -c '"command":.*\.ts"' .claude/settings.json 2>/dev/null || echo "0"
  else
    echo "0"
  fi
}

check_settings_valid() {
  if command -v node &> /dev/null; then
    if node -e "JSON.parse(require('fs').readFileSync('.claude/settings.json', 'utf8'))" 2>/dev/null; then
      echo "✓ Yes"
    else
      echo "✗ No - Invalid JSON"
    fi
  else
    echo "? (Node.js not available)"
  fi
}

get_hook_preset() {
  if [ ! -f ".claude/settings.json" ]; then
    echo "None"
    return
  fi

  local hook_count=$(count_active_hooks)

  if [ "$hook_count" -eq 0 ]; then
    echo "None (hooks disabled)"
  elif [ "$hook_count" -ge 10 ]; then
    echo "All ($hook_count hooks)"
  elif [ "$hook_count" -ge 4 ]; then
    echo "Custom ($hook_count hooks)"
  elif grep -q "react_quality" .claude/settings.json 2>/dev/null; then
    echo "React-focused ($hook_count hooks)"
  elif grep -q "security_scan" .claude/settings.json 2>/dev/null; then
    if grep -q "code_quality" .claude/settings.json 2>/dev/null; then
      echo "Quality-focused ($hook_count hooks)"
    else
      echo "Security-focused ($hook_count hooks)"
    fi
  else
    echo "Custom ($hook_count hooks)"
  fi
}

# Generate STATUS.md
cat > "$OUTPUT" << EOF
# Claude Code Configuration Status

**Last Updated:** $(date '+%Y-%m-%d %H:%M:%S')

## Active Components

### Core Agents (Always Enabled)
- **Count:** $(count_core_agents) agents
- **Location:** \`.claude/core/agents/\`
- **Status:** Always active, auto-invoked based on context

### Core Commands (Always Available)
- **Count:** $(count_core_commands) commands
- **Location:** \`.claude/core/commands/\`
- **Usage:** Type \`/command-name\` in Claude Code

### Enabled Skills
- **Active:** $(count_enabled_skills) skills (in \`.claude/core/skills/\`)
- **Available:** $(count_example_skills) skills (in \`.claude/examples/skills/\`)
- **To enable more:** Copy from examples to core:
  \`\`\`bash
  cp -r .claude/examples/skills/<skill-name> .claude/core/skills/
  \`\`\`

### Quality Hooks
- **Configuration:** $(get_hook_preset)
- **To change:** Run \`/enable-hook <preset>\` or edit \`.claude/settings.json\`
- **Available presets:** quality-focused, security-focused, react-focused, all

## Configuration Details

**Settings File:** \`.claude/settings.json\`
**Valid JSON:** $(check_settings_valid)

## Quick Actions

### Enable More Features

\`\`\`bash
# Enable a skill category
cp -r .claude/examples/skills/next .claude/core/skills/

# Enable hooks
/enable-hook quality-focused

# Validate your setup
./quick-validate.sh
\`\`\`

### View Your Configuration

\`\`\`bash
# See all enabled skills
ls .claude/core/skills/

# See hook configuration
cat .claude/settings.json | grep -A 20 "PostToolUse"

# See available optional features
ls .claude/examples/skills/
\`\`\`

## Validation

Run comprehensive validation to ensure everything is working:

\`\`\`bash
./quick-validate.sh
\`\`\`

This checks:
- All core files exist
- JSON configuration is valid
- Component counts are correct
- TypeScript compiles (if applicable)

## Next Steps

1. **Customize:** Enable additional skills/hooks based on your stack
2. **Validate:** Run \`./quick-validate.sh\` after changes
3. **Learn:** Read \`.claude/FIRST_STEPS.md\` for tutorials
4. **Explore:** Browse \`.claude/examples/\` for optional features

## Documentation

- **FIRST_STEPS.md** - Your first 5 minutes with Claude Code
- **CLAUDE.md** - Complete development guide
- **README.md** - User-facing documentation
- **.claude/docs/** - Detailed guides by topic

---

*This file is automatically generated by \`.claude/scripts/generate-status.sh\`*
*Regenerate with: \`bash .claude/scripts/generate-status.sh\`*
EOF

echo -e "${GREEN}✓${NC} STATUS.md generated at: $OUTPUT"
